pipeline:
  identifier: Build_GuliyevaAytaj_spring_boot_shop_1723509970642
  name: Build spring-boot-shop
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1723509943998
        repoName: GuliyevaAytaj/spring-boot-shop
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: build
                  identifier: build
                  spec:
                    connectorRef: account.harnessImage
                    image: gradle:7.6-jdk11
                    shell: Sh
                    command: ./gradlew clean build
              - step:
                  type: Run
                  name: check dependencies
                  identifier: check_dependencies
                  spec:
                    connectorRef: account.harnessImage
                    image: gradle:7.6-jdk11
                    shell: Sh
                    command: ./gradlew dependencyCheckAnalyze --info
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
